### ISSUE TITLE
Find suitable calendar component for hotely

### ISSUE THREAD

**Issue by rizgust** [glovory/UI-library-vue#186]
we need to find suitable component or library for calendar in hotely

**Comment by rizgust** [comment]
for this task, please list all suitable components for gantt calendar. with its pros & cons

**Comment by yogaajie2** [comment]
1. TOAST UI Calendar [(https://ui.toast.com/tui-calendar)](url)
- Pros:
Vue wrapper component available
Various view types
Drag & drop support
Resizing support
Popups
- Cons:
Might need dependency from other TOAST UI components
2. Daykeep Calendar Quasar [(https://github.com/stormseed/daykeep-calendar-quasar)](url)
- Pros:
Quasar based
Various view types
- Cons:
Intended for Quasar v1
No drag & drop support
No resizing support
No popups, only modals/dialog box
3. Vue Ganttastic [(https://infectoone.github.io/vue-ganttastic-homepage/#/)](url)
- Pros:
Vue 3 Support
Highly customizable
Drag & drop support
Resizing support
- Cons:
Limited view types
No popups
4. vue-dj-gantt [(https://github.com/jdoleczek/vue-dj-gantt)](url)
- Pros:
Vue 3 Support
Zoom in/zoom out
Drag & drop support
Resizing support
- Cons:
Limited view types
No popups
Limited documentation
Limited support & customization

_This list will be updated when other suitable components is found_

**Comment by rizgust** [comment]
thanks for your update, we will use #3, Vue Ganttastic, since it more up to date and more stable.
